[world]
kind = "WorldContract"
class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
original_class_hash = "0x76ced5a15cb43c7be7176cff4779cd57c56638a46ddf2c9da709d22298c5e5a"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x5433c39e1f815debb12d7620024788b11c3de7b7f0762f3f121a5ea631f4f67"
transaction_hash = "0x64b2ede2a7cbd5860b309a11ec73dd4679bfdf60f2a6507a7104af450289aa1"
block_number = 20
seed = "dojo_starter_all_types"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x200be7007f709caa667def7a6c0268edfaaf45b209381530c2942322cc66632"
class_hash = "0x8966968c31ddfd223c3196cf854b04a0112f1c925528a6b045d4b7db2d7d3a"
original_class_hash = "0x8966968c31ddfd223c3196cf854b04a0112f1c925528a6b045d4b7db2d7d3a"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_starter_all_types-change_types-53cc9820.json"
reads = []
writes = [
    "dojo_starter_all_types-UnsignedData",
    "dojo_starter_all_types-SignedData",
    "dojo_starter_all_types-StringData",
    "dojo_starter_all_types-ArrayData",
    "dojo_starter_all_types-ToupleData",
]
init_calldata = []
tag = "dojo_starter_all_types-change_types"
manifest_name = "dojo_starter_all_types-change_types-53cc9820"

[[contracts]]
kind = "DojoContract"
address = "0x3ef6bccbbf0571bd0898c2e75ed0f25b3891f6e502e3e07364f316a58e988b"
class_hash = "0x55a36c6dc0b3deb8b934a5194b9e03da42c5a05e592c0f4fc9b1bcc6fc233bd"
original_class_hash = "0x55a36c6dc0b3deb8b934a5194b9e03da42c5a05e592c0f4fc9b1bcc6fc233bd"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_starter_all_types-spawn_types-58c4e5d9.json"
reads = []
writes = [
    "dojo_starter_all_types-UnsignedData",
    "dojo_starter_all_types-SignedData",
    "dojo_starter_all_types-StringData",
    "dojo_starter_all_types-ArrayData",
    "dojo_starter_all_types-ToupleData",
]
init_calldata = []
tag = "dojo_starter_all_types-spawn_types"
manifest_name = "dojo_starter_all_types-spawn_types-58c4e5d9"

[[contracts]]
kind = "DojoContract"
address = "0x557a16c63b3fd5331f8241fe2e073f73e01686963c3dfe66cc8a0e457bec274"
class_hash = "0x38a9affb7552aedbb53929ddf70939a884b9d2431f0b8dc933ad96867c20c19"
original_class_hash = "0x38a9affb7552aedbb53929ddf70939a884b9d2431f0b8dc933ad96867c20c19"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_starter_all_types-test_all_inputs-7f6a9f36.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_starter_all_types-test_all_inputs"
manifest_name = "dojo_starter_all_types-test_all_inputs-7f6a9f36"

[[models]]
kind = "DojoModel"
class_hash = "0x4973fa5d694bca798fbeb57f5c5b75813042ed4b0025a3f76e791d3465dfdfa"
original_class_hash = "0x4973fa5d694bca798fbeb57f5c5b75813042ed4b0025a3f76e791d3465dfdfa"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-ArrayData-5208fece.json"
tag = "dojo_starter_all_types-ArrayData"
manifest_name = "dojo_starter_all_types-ArrayData-5208fece"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "exists"
type = "bool"
key = false

[[models.members]]
name = "testArray"
type = "Array<u8>"
key = false

[[models.members]]
name = "testArray1"
type = "Array<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5b5f32b79b35ee84a8bffea958546f39c87cf4ab590b86e48c8e98c7d248c7a"
original_class_hash = "0x5b5f32b79b35ee84a8bffea958546f39c87cf4ab590b86e48c8e98c7d248c7a"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-AttackResult-718864ba.json"
tag = "dojo_starter_all_types-AttackResult"
manifest_name = "dojo_starter_all_types-AttackResult-718864ba"

[[models.members]]
name = "combatant_id"
type = "u128"
key = true

[[models.members]]
name = "round"
type = "u32"
key = true

[[models.members]]
name = "attack_id"
type = "u128"
key = false

[[models.members]]
name = "target"
type = "u128"
key = false

[[models.members]]
name = "effect"
type = "AttackEffect"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1a4e11bec4423eb16abf9d6f4e1e90dea798b1dd7c46fad93598f2e8c93d7f9"
original_class_hash = "0x1a4e11bec4423eb16abf9d6f4e1e90dea798b1dd7c46fad93598f2e8c93d7f9"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-EmitEvent-2be394b9.json"
tag = "dojo_starter_all_types-EmitEvent"
manifest_name = "dojo_starter_all_types-EmitEvent-2be394b9"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "u_thrity_two"
type = "u32"
key = false

[[models.members]]
name = "u_onetwoeight"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x157aef1198d7c6358c70c0539cee149c17d472661f10878868d84f8547e4e52"
original_class_hash = "0x157aef1198d7c6358c70c0539cee149c17d472661f10878868d84f8547e4e52"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-ItemMap-64efd42c.json"
tag = "dojo_starter_all_types-ItemMap"
manifest_name = "dojo_starter_all_types-ItemMap-64efd42c"

[[models.members]]
name = "custom"
type = "bool"
key = true

[[models.members]]
name = "blobert_trait"
type = "BlobertTrait"
key = true

[[models.members]]
name = "blobert_trait_id"
type = "u8"
key = true

[[models.members]]
name = "item_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x726926e64597836fedc8165a035a2caf3c920959fcbf219e05e0a2a7534bb94"
original_class_hash = "0x726926e64597836fedc8165a035a2caf3c920959fcbf219e05e0a2a7534bb94"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-LargeData-58fc27ad.json"
tag = "dojo_starter_all_types-LargeData"
manifest_name = "dojo_starter_all_types-LargeData-58fc27ad"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "exists"
type = "bool"
key = false

[[models.members]]
name = "felt"
type = "felt252"
key = false

[[models.members]]
name = "uTwoFiveSix"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x565f2e443541a2ab3fe640594409370916bfd383b8696674b78c635691e065b"
original_class_hash = "0x565f2e443541a2ab3fe640594409370916bfd383b8696674b78c635691e065b"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-SignedData-630a557b.json"
tag = "dojo_starter_all_types-SignedData"
manifest_name = "dojo_starter_all_types-SignedData-630a557b"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "exists"
type = "bool"
key = false

[[models.members]]
name = "iEight"
type = "i8"
key = false

[[models.members]]
name = "iSixteen"
type = "i16"
key = false

[[models.members]]
name = "iThirtyTwo"
type = "i32"
key = false

[[models.members]]
name = "iSixtyFour"
type = "i64"
key = false

[[models.members]]
name = "iOneTwentyEight"
type = "i128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x259aa6ce7715877fd23ea1a99993cb64987205efcd87571b75b311250083492"
original_class_hash = "0x259aa6ce7715877fd23ea1a99993cb64987205efcd87571b75b311250083492"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-StringData-d0ada203.json"
tag = "dojo_starter_all_types-StringData"
manifest_name = "dojo_starter_all_types-StringData-d0ada203"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "exists"
type = "bool"
key = false

[[models.members]]
name = "byte_array"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4065f06c8150045df7571668d38fa390c9d18dff7447c717512b6699ab7c111"
original_class_hash = "0x4065f06c8150045df7571668d38fa390c9d18dff7447c717512b6699ab7c111"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-TestingEnum-6d044fe7.json"
tag = "dojo_starter_all_types-TestingEnum"
manifest_name = "dojo_starter_all_types-TestingEnum-6d044fe7"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "exists"
type = "bool"
key = false

[[models.members]]
name = "traits"
type = "TestingEnumValue"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x22e6d7c8db19a53bc8f576a9b5a14a69313beac0bf2c47e27c0e195276a7e3e"
original_class_hash = "0x22e6d7c8db19a53bc8f576a9b5a14a69313beac0bf2c47e27c0e195276a7e3e"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-ToupleData-76c041d5.json"
tag = "dojo_starter_all_types-ToupleData"
manifest_name = "dojo_starter_all_types-ToupleData-76c041d5"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "exists"
type = "bool"
key = false

[[models.members]]
name = "touple"
type = "(u8, u16)"
key = false

[[models.members]]
name = "touple1"
type = "(i8, i16,u64)"
key = false

[[models.members]]
name = "touple2"
type = "(felt252, u256)"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x754b0935198457e45d666bc97325d546e943ac989b01351925ac3611dcce92b"
original_class_hash = "0x754b0935198457e45d666bc97325d546e943ac989b01351925ac3611dcce92b"
abi = "manifests/dev/deployment/abis/models/dojo_starter_all_types-UnsignedData-3878fc42.json"
tag = "dojo_starter_all_types-UnsignedData"
manifest_name = "dojo_starter_all_types-UnsignedData-3878fc42"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "exists"
type = "bool"
key = false

[[models.members]]
name = "uEight"
type = "u8"
key = false

[[models.members]]
name = "uSixteen"
type = "u16"
key = false

[[models.members]]
name = "uThirtyTwo"
type = "u32"
key = false

[[models.members]]
name = "uSixtyFour"
type = "u64"
key = false

[[models.members]]
name = "uOneTwentyEight"
type = "u128"
key = false
