// Generated by dojo-bindgen on Thu, 29 Aug 2024 01:27:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace dojo_starter_all_types {
    // Model definition for `dojo_starter_all_types::models::all_types::UnsignedData` model
    public class UnsignedData : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("exists")]
        public bool exists;

        [ModelField("uEight")]
        public byte uEight;

        [ModelField("uSixteen")]
        public ushort uSixteen;

        [ModelField("uThirtyTwo")]
        public uint uThirtyTwo;

        [ModelField("uSixtyFour")]
        public ulong uSixtyFour;

        [ModelField("uOneTwentyEight")]
        public BigInteger uOneTwentyEight;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        