// Generated by dojo-bindgen on Thu, 29 Aug 2024 01:27:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `core::byte_array::ByteArray` struct
[Serializable]
public struct ByteArray {
    public string[] data;
    public FieldElement pending_word;
    public uint pending_word_len;
}

// Type definition for `dojo::model::layout::FieldLayout` struct
[Serializable]
public struct FieldLayout {
    public FieldElement selector;
    public Layout layout;
}

// Type definition for `core::option::Option::<core::integer::u32>` enum
public abstract record Option<A>() : Enum {
    public record Some(A value) : Option<A>;
    public record None() : Option<A>;
}

// Type definition for `dojo::model::layout::Layout` enum
public abstract record Layout() : Enum {
    public record Fixed(byte[] value) : Layout;
    public record Struct(FieldLayout[] value) : Layout;
    public record Tuple(Layout[] value) : Layout;
    public record Array(Layout[] value) : Layout;
    public record ByteArray() : Layout;
    public record Enum(FieldLayout[] value) : Layout;
}


namespace dojo_starter_all_types {
    // Model definition for `dojo_starter_all_types::models::all_types::ArrayData` model
    public class ArrayData : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("exists")]
        public bool exists;

        [ModelField("testArray")]
        public byte[] testArray;

        [ModelField("testArray1")]
        public uint[] testArray1;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        