// Generated by dojo-bindgen on Thu, 29 Aug 2024 01:27:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter_all_types::models::all_types::Seed` struct
[Serializable]
public struct Seed {
    public byte background;
    public ushort foreground;
    public uint after;
}

// Type definition for `dojo_starter_all_types::models::all_types::TestingEnumValue` enum
public abstract record TestingEnumValue() : Enum {
    public record Regular(Seed value) : TestingEnumValue;
    public record Custom(byte value) : TestingEnumValue;
}


namespace dojo_starter_all_types {
    // Model definition for `dojo_starter_all_types::models::all_types::TestingEnum` model
    public class TestingEnum : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("exists")]
        public bool exists;

        [ModelField("traits")]
        public TestingEnumValue traits;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        