// Generated by dojo-bindgen on Thu, 29 Aug 2024 01:27:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `dojo_starter_all_types::models::all_types::BlobertTrait` enum
public abstract record BlobertTrait() : Enum {
    public record Background() : BlobertTrait;
    public record Armour() : BlobertTrait;
    public record Jewelry() : BlobertTrait;
    public record Mask() : BlobertTrait;
    public record Weapon() : BlobertTrait;
}


namespace dojo_starter_all_types {
    // Model definition for `dojo_starter_all_types::models::all_types::ItemMap` model
    public class ItemMap : ModelInstance {
        [ModelField("custom")]
        public bool custom;

        [ModelField("blobert_trait")]
        public BlobertTrait blobert_trait;

        [ModelField("blobert_trait_id")]
        public byte blobert_trait_id;

        [ModelField("item_id")]
        public BigInteger item_id;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        