// Generated by dojo-bindgen on Thu, 29 Aug 2024 01:27:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;


namespace dojo_starter_all_types {
    // Model definition for `dojo_starter_all_types::models::all_types::SignedData` model
    public class SignedData : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("exists")]
        public bool exists;

        [ModelField("iEight")]
        public sbyte iEight;

        [ModelField("iSixteen")]
        public short iSixteen;

        [ModelField("iThirtyTwo")]
        public int iThirtyTwo;

        [ModelField("iSixtyFour")]
        public long iSixtyFour;

        [ModelField("iOneTwentyEight")]
        public BigInteger iOneTwentyEight;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        