// Generated by dojo-bindgen on Thu, 29 Aug 2024 01:27:58 +0000. Do not modify this file manually.
using System;
using Dojo;
using Dojo.Starknet;
using System.Reflection;
using System.Linq;
using System.Collections.Generic;
using Enum = Dojo.Starknet.Enum;

// Type definition for `core::integer::u256` struct
[Serializable]
public struct U256 {
    public BigInteger low;
    public BigInteger high;
}


namespace dojo_starter_all_types {
    // Model definition for `dojo_starter_all_types::models::all_types::LargeData` model
    public class LargeData : ModelInstance {
        [ModelField("player")]
        public FieldElement player;

        [ModelField("exists")]
        public bool exists;

        [ModelField("felt")]
        public FieldElement felt;

        [ModelField("uTwoFiveSix")]
        public U256 uTwoFiveSix;

        // Start is called before the first frame update
        void Start() {
        }
    
        // Update is called once per frame
        void Update() {
        }
    }
}

        